wfp_geonode/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2017 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import url, include

from django.conf import settings
from django.views.generic import TemplateView
from django.conf import settings
from geonode.urls import urlpatterns

urlpatterns += [
## include your urls here

]

urlpatterns = [
   url(r'^/?$',
       TemplateView.as_view(template_name='site_index.html'),
       name='home'),
 ] + urlpatterns


if "wfpdocs" in settings.INSTALLED_APPS:
    urlpatterns += [  # '',
        url(r'^wfpdocs/',
             include('wfpdocs.urls')),
    ]

if "trainings" in settings.INSTALLED_APPS:
 urlpatterns += [  # '',
     url(r'^trainings/',
          include('trainings.urls')),
 ]

if "wfpgis" in settings.INSTALLED_APPS:
     urlpatterns += [  # '',
         url(r'^wfpgis/',
              include('wfpgis.urls')),
     ]

wfpdocs/urls.py
#!/usr/bin/env python
#########################################################################
#
# Copyright (C) 2012-2015 Paolo Corti, pcorti@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.conf import settings

from .views import DocumentUploadView, DocumentUpdateView

from .api import WFPDocumentResource, CategoryResource, TagResourceSimple, RegionResource
from feeds import WFPDocumentsFeed

from geonode.api import api as geonode_api
from geonode.api.urls import api

from wfpdocs import views as wfpdocs


api.api_name = "v2.10"
api.register(WFPDocumentResource())
api.register(CategoryResource())
api.unregister(geonode_api.TagResource())
api.register(TagResourceSimple())
api.unregister(geonode_api.RegionResource())
api.register(RegionResource())


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='wfpdocs/document_list.html'), name='wfpdocs_browse'),
    url(r'^rss/$', WFPDocumentsFeed(), name='wfpdocs_rss'),
    url(r'^api/', include(api.urls)),
    url(r'^upload/$', login_required(DocumentUploadView.as_view()), name='wfpdocs_upload'),
    url(r'^(?P<slug>[\w-]+)/$', wfpdocs.document_detail, name='wfpdocs_detail'),
    url(r'^(?P<slug>[\w-]+)/update$', login_required(DocumentUpdateView.as_view()),
        name="wfpdocs_update"),
    url(r'^(?P<slug>[\w-]+)/remove$', wfpdocs.document_remove, name='wfpdocs_remove'),
    url(r'^(?P<slug>[\w-]+)/download/?$', wfpdocs.document_download, name='wfpdocs_download'),
]

wfpgis/urls.py
#!/usr/bin/env python
#########################################################################
#
# Copyright (C) 2012-2015 Paolo Corti, pcorti@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import url, include

from tastypie.api import Api

from api import OfficeResource, EmployeeResource

v1_api = Api(api_name='api')
v1_api.register(OfficeResource())
v1_api.register(EmployeeResource())

urlpatterns = [
    url(r'^api/', include(v1_api.urls)),
]

wfpdocs/models.py
#!/usr/bin/env python
#########################################################################
#
# Copyright (C) 2012-2015 Paolo Corti, pcorti@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

import os
import logging
import uuid

from django.conf import settings
from django.db import models
from django.db import IntegrityError
from django.db.models import signals
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.staticfiles import finders
from django.utils.text import slugify

from geonode.base.models import ResourceBase, resourcebase_post_save
from geonode.layers.models import Layer

IMGTYPES = ['jpg', 'jpeg', 'tif', 'tiff', 'png', 'gif']

logger = logging.getLogger(__name__)


class Category(models.Model):
    """
    A WFM Map Document category
    """

    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'


class WFPDocument(ResourceBase):
    """
    A WFP document
    """

    source_help_text = _('Please provide Source for the map - ex: WFP CO Afghanistan')
    orientation_help_text = _('Orientation of the map')
    format_help_text = _('Format of the map')
    categories_help_text = _('Assign one or more categories to the map.')

    ORIENTATION_CHOICES = (
        (0, 'Landscape'),
        (1, 'Portrait'),
    )

    FORMAT_CHOICES = (
        (4, 'A4'),
        (0, 'A0'),
        (1, 'A1'),
        (2, 'A2'),
        (3, 'A3'),
    )

    source = models.CharField(max_length=255, help_text=source_help_text)
    orientation = models.IntegerField(
        'Orientation', choices=ORIENTATION_CHOICES, default=0,
        help_text=orientation_help_text
    )
    page_format = models.IntegerField(
        'Format', choices=FORMAT_CHOICES, default=0,
        help_text=format_help_text
    )
    doc_file = models.FileField(upload_to='documents', max_length=255, verbose_name=_('File'))
    extension = models.CharField(max_length=128, blank=True, null=True)
    last_version = models.BooleanField(default=False)
    date_updated = models.DateTimeField(auto_now=True, blank=False, null=False)
    # TODO use django-autoslug
    slug = models.SlugField(unique=True, max_length=255, blank=True)
    categories = models.ManyToManyField(
        Category, verbose_name='categories', blank=True,
        help_text=categories_help_text
    )
    layers = models.ManyToManyField(Layer, blank=True)

    def __str__(self):
        return '%s' % self.source

    def get_absolute_url(self):
        return reverse('wfpdocs_detail', args=(self.slug,))

    def get_file_size(self):
        try:
            num = self.doc_file.size
            for x in ['bytes', 'KB', 'MB', 'GB', 'TB']:
                if num < 1024.0:
                    return "%3.1f %s" % (num, x)
                num /= 1024.0
        except:
            return 0

    def get_regions(self):
        regions = []
        for region in self.regions.all():
            regions.append(region.name)
        return ', '.join(regions)
    get_regions.short_description = 'Regions'

    def get_categories(self):
        categories = []
        for category in self.categories.all():
            categories.append(category.name)
        return ", ".join(categories)
    get_categories.short_description = 'Categories'

    def get_layers(self):
        layers = []
        for layer in self.layers.all():
            layers.append(layer.name)
        return ", ".join(layers)
    get_layers.short_description = 'Layers'

    @property
    def class_name(self):
        return self.__class__.__name__

    def _render_thumbnail(self):
        from cStringIO import StringIO

        size = 200, 150

        try:
            from PIL import Image, ImageOps
        except ImportError, e:
            logger.error(
                '%s: Pillow not installed, cannot generate thumbnails.' %
                e)
            return None

        try:
            # if wand is installed, than use it for pdf thumbnailing
            from wand import image
        except:
            wand_available = False
        else:
            wand_available = True

        if wand_available and self.extension and self.extension.lower(
        ) == 'pdf' and self.doc_file:
            logger.debug(
                u'Generating a thumbnail for document: {0}'.format(
                    self.title))
            try:
                with image.Image(filename=self.doc_file.path) as img:
                    img.sample(*size)
                    return img.make_blob('png')
            except:
                logger.debug('Error generating the thumbnail with Wand, cascading to a default image...')
        # if we are still here, we use a default image thumb
        if self.extension and self.extension.lower() in IMGTYPES and self.doc_file:

            img = Image.open(self.doc_file.path)
            img = ImageOps.fit(img, size, Image.ANTIALIAS)
        else:
            filename = finders.find('documents/{0}-placeholder.png'.format(self.extension), False) or \
                finders.find('documents/generic-placeholder.png', False)

            if not filename:
                return None

            img = Image.open(filename)

        imgfile = StringIO()
        img.save(imgfile, format='PNG')
        return imgfile.getvalue()

    def save(self, *args, **kwargs):
        # we may want to set up slug explicitely
        if self.slug is None or self.slug == '':
            slug = slugify(unicode(self.title))[0:250]
            self.slug = slug
        while True:
            try:
                return super(WFPDocument, self).save(*args, **kwargs)
            except IntegrityError:
                # generate a new slug
                print 'Integrity Error...'
                self.slug = '%s-%s' % (slug, (WFPDocument.objects.filter(title=self.title).count() + 1))


def pre_save_wfpdocument(instance, sender, **kwargs):

    base_name, extension, doc_type = None, None, None

    if instance.doc_file:
        base_name, extension = os.path.splitext(instance.doc_file.name)
        instance.extension = extension[1:]
        doc_type_map = settings.DOCUMENT_TYPE_MAP
        if doc_type_map is None:
            doc_type = 'other'
        else:
            if instance.extension in doc_type_map:
                doc_type = doc_type_map[''+instance.extension]
            else:
                doc_type = 'other'
        instance.doc_type = doc_type

    if not instance.uuid:
        instance.uuid = str(uuid.uuid1())
    instance.csw_type = 'wfpdocument'

    if instance.abstract == '' or instance.abstract is None:
        instance.abstract = 'No abstract provided'

    if instance.title == '' or instance.title is None:
        instance.title = instance.doc_file.name

    # TODO maybe we want to set based on the extent of the layers
    instance.bbox_x0 = -180
    instance.bbox_x1 = 180
    instance.bbox_y0 = -90
    instance.bbox_y1 = 90


def create_thumbnail(sender, instance, created, **kwargs):
    from .tasks import create_wfpdoc_thumbnail

    create_wfpdoc_thumbnail.delay(object_id=instance.id)

signals.pre_save.connect(pre_save_wfpdocument, sender=WFPDocument)
signals.post_save.connect(create_thumbnail, sender=WFPDocument)
signals.post_save.connect(resourcebase_post_save, sender=WFPDocument)

wfpgis/models.py
#!/usr/bin/env python
#########################################################################
#
# Copyright (C) 2012-2015 Paolo Corti, pcorti@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.gis.db import models as gismodels

from geonode.people.models import Profile


class Office(gismodels.Model):
    """
    Model for WFP Office.
    """
    wfpid = gismodels.IntegerField(null=True, blank=True)
    place = gismodels.CharField(max_length=254)
    facility = gismodels.CharField(max_length=254, null=True, blank=True)
    status = gismodels.CharField(max_length=254, null=True, blank=True)
    iso3 = gismodels.CharField(max_length=254, null=True, blank=True)
    iso3_op = gismodels.CharField(max_length=254, null=True, blank=True)
    country = gismodels.CharField(max_length=254, null=True, blank=True)
    locprecisi = gismodels.CharField(max_length=254, null=True, blank=True)
    latitude = gismodels.FloatField(null=True, blank=True)
    longitude = gismodels.FloatField(null=True, blank=True)
    wfpregion = gismodels.CharField(max_length=254, null=True, blank=True)
    nat_staff = gismodels.IntegerField(null=True, blank=True)
    int_staff = gismodels.IntegerField(null=True, blank=True)
    lastcheckd = gismodels.DateField(null=True, blank=True)
    remarks = gismodels.CharField(max_length=254, null=True, blank=True)
    source = gismodels.CharField(max_length=254, null=True, blank=True)
    createdate = gismodels.DateField(null=True, blank=True)
    updatedate = gismodels.DateField(null=True, blank=True)
    objectidol = gismodels.FloatField(null=True, blank=True)
    precisiono = gismodels.CharField(max_length=254, null=True, blank=True)
    verifiedol = gismodels.CharField(max_length=254, null=True, blank=True)
    geometry = gismodels.PointField()
    objects = gismodels.GeoManager()

    def __unicode__(self):
        return '%s' % (self.place)

    class Meta:
        ordering = ['place']


class Employee(models.Model):
    """
    Model for WFP Profile.
    """

    GIS_LEVEL_CHOICES = (
        (0, 'Basic'),
        (1, 'Intermediate'),
        (2, 'Advanced'),
    )

    DUTIES_CHOICES = (
        (0, 'GIS'),
        (1, 'Not GIS')
    )

    gis_level = models.IntegerField(null=True, blank=True, choices=GIS_LEVEL_CHOICES)
    duties_type = models.IntegerField(blank=True, null=True, choices=DUTIES_CHOICES)
    profile = models.OneToOneField(Profile, primary_key=True)
    office = models.ForeignKey(Office, null=True, blank=True)

    @property
    def geometry(self):
        return self.office.geometry

    @property
    def place(self):
        return self.office.place

    @property
    def country(self):
        return self.office.country

    @property
    def wfpregion(self):
        return self.office.wfpregion

    @property
    def facility(self):
        return self.office.facility

    @property
    def name(self):
        return self.profile.name

    @property
    def position(self):
        return self.profile.position

    def __unicode__(self):
        if self.office:
            return '%s in %s' % (self.profile.get_full_name(), self.office.place)
        else:
            return u''

class CustomThumbnail(models.Model):
    """
    Model for custom thumbnails for WFP GeoNode objects
    """
    thumbnail = models.ImageField(upload_to='custom_thumbs')
    title = models.CharField(max_length=255)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __unicode__(self):
        return self.title

wfpdocs/templates/wfpdocs/document_base.html
{% extends "site_base.html" %}
{% load i18n %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}documents{% endblock %}

{% block body_outer %}
{% block body %}{% endblock body %}
{% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

wfpdocs/templates/wfpdocs/document_detail.html
{% extends "wfpdocs/document_base.html" %}
{% load i18n %}
{% load dialogos_tags %}
{% load agon_ratings_tags %}
{% load bootstrap_tags %}

{% load base_tags %}
{% load guardian_tags %}

{% block title %}{{ resource.title }} — {{ block.super }}{% endblock %}

{% block head %}

{{ block.super }}
{% endblock %}

{% block body_class %}documents{% endblock %}

{% block body_outer %}

<div class="page-header">
  <h2>{{ resource.title }}</h2>
</div>

<div class="row">
  <div class="col-md-8">

    {% get_obj_perms request.user for resource.get_self_resource as "perms" %}
    {% if "download_resourcebase" in perms %}
      {% if resource.extension|lower in imgtypes and resource.doc_file %}
      <div id="embedded_map">
        <a style="text-decoration:none;" href="{% url "wfpdocs_download" resource.slug %}" target="_blank">
          <img src="{% url "wfpdocs_download" resource.slug %}" width='100%' />
        </a>
      </div>
      {% else %}
      <p><a href="{% url "wfpdocs_download" resource.slug %}" target="_blank">Download the {{ resource }} document</a></p>
      {%  endif %}
    {%  endif %}

    <div class="documents-actions">
      {% include "_actions.html" %}
    </div>

    <div class="tab-content">
      <!-- static map content -->
      <article class="description tab-pane active" id="info">
        <dl class="dl-horizontal">
          <dt>{% trans "Title" %}</dt>
          <dd>{{ resource.title|truncatechars:80 }}</dd>
          <dt>{% trans resource.date_type|title %} {% trans "Date" %}</dt>
          <dd>{{ resource.date }}</dd>
          <dt>{% trans "Page Format" %}</dt>
          <dd>{{ resource.get_page_format_display}}</dd>
          <dt>{% trans "Orientation" %}</dt>
          <dd>{{ resource.get_orientation_display }}</dd>
          <dt>{% trans "Source" %}</dt>
          <dd>{{ resource.source }}</dd>
          <dt>{% trans "Regions" %}</dt>
          <dd>
            {% for region in resource.regions.all %}
              <a href="/wfpdocs/?regions__slug__in={{ region.name }}">{{ region.name }}</a>
            {% endfor %}
            </br>
          </dd>
          <dt>{% trans "Categories" %}</dt>
          <dd>
            {% for category in resource.categories.all %}
              <a href="/wfpdocs/?categories__name__in={{ category.name }}">{{ category.name }}</a>
            {% endfor %}
            </br>
          </dd>
          <dt>{% trans "Keywords" %}</dt>
          <dd>
            {% for keyword in resource.keywords.all %}
              <a href="/wfpdocs/?keywords__slug__in={{ keyword.slug }}">{{ keyword.name }}</a>
            {% endfor %}
          </dd>
        </dl>
      </article>
      <!-- end of static map content -->

      {% block social_links %}
        {% include "social_links.html" %}
      {% endblock %}

      <article id="comments" class="tab-pane">
      {% include "_comments.html" %}
      </article>

      <article id="rate" class="tab-pane">
        <!-- TODO: Move this to a reusable template snippet -->
        {% if request.user.is_authenticated %}
        <h4>{% trans "Rate this document" %}</h4>
        {% user_rating request.user resource "document" as user_document_rating %}
        <div id="user_rating" class="category-layer" data-score="{{user_document_rating}}"></div>
        {% endif %}
        <h4>{% trans 'Average Rating' %}</h4>
        {% overall_rating resource "document" as document_rating %}
        {% num_ratings resource as num_votes %}
        <div class="overall_rating" style="float:left" data-score="{{ document_rating }}"></div> ({{num_votes}})
        <!-- TODO: Add display of who gave what rating based -->
      </article>
    </div>
  </div>

  <div class="col-md-4">

    <ul class="list-group">
      {% get_obj_perms request.user for resource.get_self_resource as "perms" %}
      <li class="list-group-item">
      {% if "download_resourcebase" in perms %}
          <a style="text-decoration:none;" target="_blank" href="{% url "wfpdocs_download" resource.slug %}"><button class="btn btn-primary btn-md btn-block">{% trans "Download Static Map" %}</button></a>
      {%  endif %}
      </li>

      <li class="list-group-item">
        <button class="btn btn-primary btn-md btn-block" data-toggle="modal" data-target="#edit-document">{% trans "Edit Document" %}</button>
      </li>
      <div class="modal fade" id="edit-document" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">{% trans "Edit Document" %}</h4>
            </div>
            <div class="modal-body">

              <div class="row edit-modal">
                {% if "change_resourcebase" in perms or "delete_resourcebase" in perms %}
                <div class="col-sm-3">
                  <i class="fa fa-file-text-o fa-3x"></i>
                  <h4>Document</h4>
                  {% if "change_resourcebase" in perms %}
                  <a class="btn btn-default btn-block btn-xs" href="{% url "wfpdocs_update" resource.slug %}">{% trans "Edit" %}</a>
                  {% endif %}
                  {% if "delete_resourcebase" in perms %}
                  <a class="btn btn-danger btn-block btn-xs" href="{% url "wfpdocs_remove" resource.slug %}">{% trans "Remove" %}</a>
                  {% endif %}
                </div>
                {% endif %}
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
            </div>
          </div>
        </div>
      </div>

      <li class="list-group-item">
        <h4>{% trans "Layers used in this static map" %}</h4>
        {% if resource.layers %}
        <ul>
        {% for layer in resource.layers.all %}
          <li><a href="{{ layer.detail_url }}">{{ layer.name }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <p>{% trans "This static map is not linked to any layer" %}</p>
        {% endif %}
      </li>

      {% if "change_resourcebase_permissions" in perms %}
      <li class="list-group-item">
        <h4>{% trans "Permissions" %}</h4>
        <p>{% trans "Click the button below to change the permissions of this document." %}</p>
        <p><a href="#modal_perms" data-toggle="modal" class="btn btn-primary btn-block" data-target="#_permissions">{% trans "Change Document Permissions" %}</a></p>
      </li>
      {% include "_permissions_form.html" %}
      {% endif %}

      {% include "base/_resourcebase_contact_snippet.html" %}

    </ul>
  </div>
</div>
{% endblock %}

{% block extra_script %}
{% if SOCIAL_BUTTONS %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% endif %}
    {% if request.user.is_authenticated %}
        {% user_rating_js request.user resource "document" %}
    {% else %}
        {% overall_rating resource "document" as the_doc_rating %}
    {% endif %}
    {% include 'rating.html' %}
    {% include 'request_download.html' %}
    <script type="text/javascript">
        {% if SOCIAL_BUTTONS %}
        (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
        {% endif %}
    </script>
    {% include "_permissions_form_js.html" %}
{% endblock extra_script %}

wfpdocs/templates/wfpdocs/document_remove.html
{% extends "wfpdocs/document_base.html" %}
{% load i18n %}

{% block title %}{% trans "Deleting" %} {{ document.title }} — {{ block.super }}{% endblock %}

{% block body %}
<div class="page-header">
  <h2 class="page-title">{% trans "Remove Static " %}</h2>
</div>
<div class="row">
  <div class="col-md-8">
    <p class="lead">
        {% blocktrans with document.title as document_title %}
          Are you sure you want to remove <a href="{{ document.get_absolute_url }}">{{ document_title }}</a>?
        {% endblocktrans %}
      </p>
    <form action="{% url "wfpdocs_remove" document.slug %}" method="POST">
      {% csrf_token %}
      <div class="form-actions">
        <input type="submit" value="{% trans "Yes, I am sure" %}" class="btn btn-danger" />
        <a href="{{ document.get_absolute_url }}" class="btn btn-default">{% trans "No, don't remove it" %}</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

wfpdocs/templates/wfpdocs/wfpdocument_form.html
{% extends "wfpdocs/document_upload_base.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %} {% trans "Upload Static Map" %} - {{ block.super }} {% endblock %}

{% block body_class %}documents upload{% endblock body_class %}

{% comment %}
{% block head %}
    {% include "geonode/ext_header.html" %}
    {% include "geonode/app_header.html" %}
    {{ block.super }}
{% endblock %}
{% endcomment%}

{% block body %}

<div class="col-md-6">
  <form id="upload_form" method="post" enctype="multipart/form-data" action="">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
    {{ form | as_bootstrap }}
    <button type="submit" id="upload-button" class="btn btn-danger">Upload</button>
  </form>
</div>
<div class="col-md-2">
  <!-- empty space for tooltips -->
</div>

{% endblock %}

{% block sidebar %}

<div class="col-md-4">
  <h3>{% trans "Permissions"  %}</h3>
  <form id="permission_form">
    {% include "_permissions.html" %}
  </form>
</div>

{% endblock %}

{% block extra_script %}
  {% include 'metadata_form_js.html' %}
  <script type="text/javascript">
    $(function() {
      var pickerOptions = {
          format: 'YYYY-MM-DD hh:mm',
          pickDate: true,
          pickTime: true,
          language: 'en',
          icons: {
              time: 'fa fa-clock-o',
              date: 'fa fa-calendar',
              up: 'fa fa-chevron-up',
              down: 'fa fa-chevron-down'
          }
      };
      $('#id_date_picker').datetimepicker(pickerOptions);
    });
  </script>
  {% include "_permissions_form_js.html" %}

<script type="text/javascript">
    $('#id_doc_file').on('change', function(){
        if($('#id_title').val() == ''){
            $('#id_title').val($('#id_doc_file').val().replace("C:\\fakepath\\", ""));
        }
    });
    $("#resource").select2({
        minimumInputLength: 1,
        placeholder: 'Select layer, map or empty',
        width: 'element',
        ajax: {
          traditional: true,
          url: '{% url 'api_dispatch_list' api_name="v2.10" resource_name='base' %}',
          data: function(term,page){
            return {
              type__in: ['layer','map'],
              title__contains: term.replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, '')
            }
          },
          results: function(data) {
            return {
              results: $.map(data.objects,function(object){
                return {id: object.id, text: object.title};
              })
            }
          }
        }
      });
    $('#upload_form').submit(function(){
      $('#permissions').val(JSON.stringify(permissionsString($('#permission_form'),'base')));
    });
</script>
{% endblock extra_script %}